# Generated by Django 3.2.5 on 2021-07-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beegardenbackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.SmallIntegerField(max_length=5),
        ),
    ]
