# Generated by Django 3.2.5 on 2021-07-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beegardenbackapp', '0002_alter_user_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gardenarea',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.PositiveBigIntegerField(),
        ),
    ]
