# Generated by Django 3.2.5 on 2021-07-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beegardenbackapp', '0003_auto_20210701_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
